# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo_app', '0004_auto_20171108_1744'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['description'], name='projecttitleidx'),
        ),
    ]
