# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo_app', '0005_auto_20171108_1748'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='membership',
            name='repo_app_me_member__a01dc0_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='projecttitleidx',
        ),
    ]
